name = "CuTextures"
uuid = "44f18228-da5a-4172-9251-368da0040bb3"
authors = ["Cristóvão Duarte Sousa"]
version = "0.1.0"

[deps]
CUDAdrv = "c5f51814-7f29-56b8-a69c-e4d8f6be1fde"
CUDAnative = "be33ccc6-a3ff-5ff2-a52e-74243cff1e17"

[compat]
julia = "0.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
